In [4]:
import pandas as pd  
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv("./District/NumberingDistrict.csv")
#data = data.drop(columns = ['district'])
data = data.drop(columns = ['number_of_land', 'total_ntd'])
data = data[data['unit_ntd'] > 0]
delete = data[((data.unit_ntd > 3000000) |
                  (data.transaction_year < 2019) |
                  (data.land_shift_area <= 0)
                 )].index
data = data.drop(delete)
data

district  land_shift_area  complete_year  building_shift_total_area  \
0           10             4.00       0.000000                       0.00   
1            1            40.75      62.062500                     109.36   
2            1            33.81      69.000000                     109.42   
3            1            32.19      84.000000                     163.53   
4            1            60.25     108.000000                     204.79   
...        ...              ...            ...                        ...   
5905        11            13.10      67.000000                      46.22   
5906         1            24.75      89.000000                     122.18   
5907         1            29.04      73.114286                     116.50   
5908        10            41.71      87.000000                     155.03   
5909        10            22.36      91.375000                     103.03   

      num_room  num_hall  num_toilet  num_partition  management_org  \
0            0         0           0              1               0   
1            4         0           4              1               0   
2            3         2           2              1               0   
3            3         2           2              1               1   
4            3         2           3              1               1   
...        ...       ...         ...            ...             ...   
5905         3         1           1              1               0   
5906         3         2           2              1               1   
5907         5         3           3              1               0   
5908         3         2           2              1               1   
5909         3         1           1              1               0   

           unit_ntd  carpark_shift_area  carpark_ntd  transaction_year  \
0     400000.000000                0.00            0              2019   
1     108357.717630                0.00            0              2019   
2      91390.970572                0.00            0              2019   
3     128416.804256                0.00            0              2019   
4     328157.624884                0.00            0              2019   
...             ...                 ...          ...               ...   
5905  118996.105582                0.00            0              2020   
5906  196431.494516                7.42      1700000              2019   
5907  115450.643777                0.00            0              2019   
5908  243307.746888                0.00            0              2019   
5909  108026.788314                0.00            0              2019   

      transaction_month  building_age  number_of_building  number_of_carpark  
0                    10   2019.000000                   0                  0  
1                    10   1956.937500                   1                  0  
2                    10   1950.000000                   1                  0  
3                     4   1935.000000                   1                  1  
4                    10   1911.000000                   1                  0  
...                 ...           ...                 ...                ...  
5905                  1   1953.000000                   1                  0  
5906                 12   1930.000000                   1                  1  
5907                 11   1945.885714                   1                  0  
5908                 11   1932.000000                   1                  1  
5909                  8   1927.625000                   1                  0  

[5767 rows x 17 columns]

In [3]:
#Model
reg = LinearRegression()
#Data and target
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
#Cross validation
#Score = ((y_true - y_pred) ^ 2).sum()
predicted = cross_validate(reg, X, y, cv = 10)
predicted

{'fit_time': array([0.01516843, 0.00320339, 0.        , 0.00816107, 0.0022285 ,
        0.00645137, 0.        , 0.        , 0.        , 0.        ]),
 'score_time': array([0.00153303, 0.        , 0.        , 0.0012157 , 0.        ,
        0.        , 0.        , 0.        , 0.00802255, 0.        ]),
 'test_score': array([-0.08201447,  0.08445318,  0.05337321,  0.064706  ,  0.05326801,
         0.05176193,  0.04870703,  0.11955938,  0.08386588,  0.12597386])}

In [4]:
from sklearn.model_selection import cross_val_predict
predict_ntd = cross_val_predict(reg, X, y ,cv = 10)
display(abs(y - predict_ntd))
display(abs(y - predict_ntd).mean())
#predict_ntd

array([176372.73352263,  35150.38717771,  46459.69815785, ...,
        28108.57071767,  39531.93694745,  63099.43575675])

69593.67922719572

In [5]:
#Model
reg = DecisionTreeRegressor()
#Data and target
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
#Cross validation
#Score = ((y_true - y_pred) ^ 2).sum()
predicted = cross_validate(reg, X, y, cv = 10)
predicted

{'fit_time': array([0.05143881, 0.07349348, 0.05563211, 0.05501342, 0.05323124,
        0.05030656, 0.05519295, 0.05123925, 0.05476451, 0.05188847]),
 'score_time': array([0.        , 0.00099826, 0.00104237, 0.00106168, 0.        ,
        0.00737333, 0.00166297, 0.0062921 , 0.00144935, 0.        ]),
 'test_score': array([-0.32325129, -0.12096555, -0.09079942, -0.19067624, -0.96220957,
        -0.04286785, -0.48465206, -0.2686627 ,  0.08808011, -0.75690529])}

In [6]:
from sklearn.model_selection import cross_val_predict
predict_ntd = cross_val_predict(reg, X, y ,cv = 10)
display(abs(y - predict_ntd))
display(abs(y - predict_ntd).mean())
#predict_ntd

array([205000.        ,  10926.36244827,  18410.07578262, ...,
        39755.99762365, 129771.73074035, 145360.32514129])

66189.41943921825

In [ ]:
# Predict for real house
reg = DecisionTreeRegressor()
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
reg.fit(X, y)


test = [[12, 321.7, 5.0, 163.0, 4, 2, 3, 1, 1, 24.8, 0, 2020, 12, 2015, 1, 2],
        [8, 13.88, 14, 12.16, 1, 1, 1, 1, 0, 0, 0,2020, 11, 2006, 1, 0]]
reg.predict(test)

array([2158387.13928054,  202083.33333333])

In [6]:
from sklearn.svm import SVR
#Model
reg = SVR(kernel='rbf', C=1e3, gamma=0.1)
#Data and target
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
#Cross validation
#Score = ((y_true - y_pred) ^ 2).sum()
predicted = cross_validate(reg, X, y, cv = 10)


In [7]:

from sklearn.model_selection import cross_val_predict
predict_ntd = cross_val_predict(reg, X, y ,cv = 10)
display(abs(y - predict_ntd))
display(abs(y - predict_ntd).mean())
#predict_ntd

array([232404.71136066,  57276.42413281,  73398.12657615, ...,
        49802.83900687,  77456.81781119,  57971.38424586])

71524.045416027