In [1]:
import pandas as pd  
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("./District/NumberingDistrictAddress.csv")
#data = data.drop(columns = ['district'])
data = data.drop(columns = ['urban_land_use', 'number_of_land', 'total_ntd'])
data = data[data['unit_ntd'] > 0]
delete = data[((data.unit_ntd > 3000000) | 
               (data.transaction_year < 2019) | 
               (data.land_shift_area <= 0)
              )].index
data = data.drop(delete)
data

district  land_shift_area  complete_year  building_shift_total_area  \
0            1            40.75      62.062500                     109.36   
1            1            33.81      69.000000                     109.42   
2            1            32.19      84.000000                     163.53   
3            1            60.25     108.000000                     204.79   
4            1            16.99     108.000000                      80.31   
...        ...              ...            ...                        ...   
3453        11            13.10      67.000000                      46.22   
3454         1            24.75      89.000000                     122.18   
3455         1            29.04      73.114286                     116.50   
3456        10            41.71      87.000000                     155.03   
3457        10            22.36      91.375000                     103.03   

      num_room  num_hall  num_toilet  num_partition  management_org  \
0            4         0           4              1               0   
1            3         2           2              1               0   
2            3         2           2              1               1   
3            3         2           3              1               1   
4            3         2           2              1               1   
...        ...       ...         ...            ...             ...   
3453         3         1           1              1               0   
3454         3         2           2              1               1   
3455         5         3           3              1               0   
3456         3         2           2              1               1   
3457         3         1           1              1               0   

           unit_ntd  carpark_shift_area  carpark_ntd  transaction_year  \
0     108357.717630                0.00            0              2019   
1      91390.970572                0.00            0              2019   
2     128416.804256                0.00            0              2019   
3     328157.624884                0.00            0              2019   
4     138214.419126               16.80       750000              2019   
...             ...                 ...          ...               ...   
3453  118996.105582                0.00            0              2020   
3454  196431.494516                7.42      1700000              2019   
3455  115450.643777                0.00            0              2019   
3456  243307.746888                0.00            0              2019   
3457  108026.788314                0.00            0              2019   

      transaction_month  building_age  number_of_building  number_of_carpark  
0                    10   1956.937500                   1                  0  
1                    10   1950.000000                   1                  0  
2                     4   1935.000000                   1                  1  
3                    10   1911.000000                   1                  0  
4                     7   1911.000000                   1                  1  
...                 ...           ...                 ...                ...  
3453                  1   1953.000000                   1                  0  
3454                 12   1930.000000                   1                  1  
3455                 11   1945.885714                   1                  0  
3456                 11   1932.000000                   1                  1  
3457                  8   1927.625000                   1                  0  

[3376 rows x 17 columns]

In [3]:
#Model
reg = LinearRegression()
#Data and target
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
#Cross validation
#Score = ((y_true - y_pred) ^ 2).sum()
predicted = cross_validate(reg, X, y, cv = 10)
predicted

{'fit_time': array([0.0339942 , 0.00160694, 0.00199604, 0.00684309, 0.00142622,
        0.00099874, 0.        , 0.00905132, 0.00252628, 0.        ]),
 'score_time': array([0.00083184, 0.00104952, 0.        , 0.00204754, 0.00108004,
        0.        , 0.        , 0.00099444, 0.        , 0.0080018 ]),
 'test_score': array([ 0.12436502, -0.04210082,  0.16285156,  0.10781113,  0.18085914,
         0.1569336 ,  0.10890353,  0.04058648,  0.16353941,  0.20644658])}

In [4]:
from sklearn.model_selection import cross_val_predict
predict_ntd = cross_val_predict(reg, X, y ,cv = 10)
display(abs(y - predict_ntd))
display(abs(y - predict_ntd).mean())
#predict_ntd

array([31980.23047578, 31298.88117345, 11383.1007883 , ...,
        4453.41894273, 24321.61121922, 62162.49683696])

57587.36758795225

In [5]:
#Model
reg = DecisionTreeRegressor()
#Data and target
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
#Cross validation
#Score = ((y_true - y_pred) ^ 2).sum()
predicted = cross_validate(reg, X, y, cv = 10)
predicted

{'fit_time': array([0.05153966, 0.06616378, 0.0625391 , 0.03433299, 0.04682875,
        0.0464673 , 0.04690099, 0.04429555, 0.04947972, 0.05045891]),
 'score_time': array([0.        , 0.00099659, 0.        , 0.01562047, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]),
 'test_score': array([-0.36677455,  0.10588026,  0.13761009,  0.00331833,  0.25372464,
         0.00575515, -0.28103862, -0.17299845,  0.36205757,  0.42790434])}

In [6]:
from sklearn.model_selection import cross_val_predict
predict_ntd = cross_val_predict(reg, X, y ,cv = 10)
display(abs(y - predict_ntd))
display(abs(y - predict_ntd).mean())
#predict_ntd

array([ 12467.30667094,  31261.71086927,  41714.73424418, ...,
        20440.47185923,  90881.51279457, 110158.43502143])

54733.63218508309

In [7]:
# Predict for real house
reg = DecisionTreeRegressor()
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
reg.fit(X, y)


test = [[12, 321.7, 5.0, 163.0, 4, 2, 3, 1, 1, 24.8, 0, 2020, 12, 2015, 1, 2],
        [8, 13.88, 14, 12.16, 1, 1, 1, 1, 0, 0, 0,2020, 11, 2006, 1, 0]]
reg.predict(test)

array([1933333.33333333,  276000.        ])

In [8]:
from sklearn.svm import SVR
#Model
reg = SVR(kernel='rbf', C=1e3, gamma=0.1)
#Data and target
X = data.drop(columns=['unit_ntd']).values
y = data['unit_ntd'].values
#Cross validation
#Score = ((y_true - y_pred) ^ 2).sum()
predicted = cross_validate(reg, X, y, cv = 10)


In [9]:
from sklearn.model_selection import cross_val_predict
predict_ntd = cross_val_predict(reg, X, y ,cv = 10)
display(abs(y - predict_ntd))
display(abs(y - predict_ntd).mean())
#predict_ntd

array([52639.19471057, 69111.16342624, 33534.49466419, ...,
       44467.34594942, 82748.88423521, 52636.14639535])

61136.874789049834